name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: org-capture-bot
            asset_name: org-capture-bot-linux-amd64
          - os: macos-latest
            artifact_name: org-capture-bot
            asset_name: org-capture-bot-macos-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release --locked
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          overwrite: true
          tag: ${{ github.ref }}
